services:
  mysql:
    image: mysql:8.4
    container_name: app_preguntas_mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: quizapp
      MYSQL_USER: quizapp_user
      MYSQL_PASSWORD: quizapp_password
      MYSQL_ROOT_PASSWORD: "1234"
    volumes:
      - mysql_data:/var/lib/mysql

  mongo:
    image: mongo:7.0
    container_name: app_preguntas_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  libretranslate:
    image: libretranslate/libretranslate:latest
    container_name: app_preguntas_libretranslate
    ports:
      - "5000:5000"
    command: [ "--load-only", "en,es" ]

volumes:
  mysql_data:
  mongo_data:
